### ISSUE TITLE
Not clear where to click to view game!

### ISSUE THREAD

**Issue by chao-mu** [jackstenglein/chess-dojo-scheduler#473] opened 2024-04-26 08:29 UTC
In /games there's no indicator to the user that clicking a row is what they need to do to view a game. The row background changes but to me this is just indicating to the user the information beneath the pointer is highlighted - not that it has the potential to behave navigational. Changing the mouse cursor would probably bridge that gap.

**Comment by jackstenglein** [comment] 2024-08-13 01:41
Duplicate of #561

**Closed by jackstenglein** 2024-08-13 01:41 UTC
